name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
        context: .
          file: .Dockerfile
          tags: my-image-name:t10
        run: docker build . --file .Dockerfile --tag my-image-name:$(date +%s)
